CREATE TABLE IF NOT EXISTS TRANSACTIONS(
id SERIAL PRIMARY KEY,
date VARCHAR(50) NOT NULL,
shop varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
description varchar(50) not null,
price INTEGER not null
);

