package com.ang.rest.domain.entity;

public enum ProductFamily {
    DAIRY, MEAT, FRUITS_VEGETABLES, BEVERAGES, PANTRY,CLEANING_SUPPLIES,CLOTHING,
    BAKING_INGREDIENTS,CONDIMENTS,PET_SUPPLIES,SNACKS,GRAINS,FROZEN_FOODS,COOKING_ESSENTIALS,HEALTH_AND_BEAUTY,FOOD_AND_DINING}