name: Expense Tracker API CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:
    types: [custom-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build Backend with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Backend Docker Image
        run: docker build . --file ./Dockerfile --tag ghcr.io/angeloskol/expense-tracker-api:latest

      - name: Log in to GHCR
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Backend Docker Image to GHCR
        run: docker push ghcr.io/angeloskol/expense-tracker-api:latest

