name: Expense Tracker API CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:
    types: [custom-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Multi-Service Docker Compose Images
        run: docker compose build

      - name: Tag and Push Backend Image to GHCR
        run: |
          docker tag expense-tracker_backend ghcr.io/angeloskol/expense-tracker-backend:latest
          docker push ghcr.io/angeloskol/expense-tracker-backend:latest

      - name: Tag and Push Database Image to GHCR
        run: |
          docker tag expense-tracker_database ghcr.io/angeloskol/expense-tracker-database:latest
          docker push ghcr.io/angeloskol/expense-tracker-database:latest
